title: Settings
data:
  site_name: 'Limelight SMP'
  personality: formal
  show_signup: false
  social:
    -
      id: jCWvKJYY
      name: Twitter
      url: 'https://twitter.com/LimelightSMP'
      icon: site/social-icons/twitter.svg
      icon_field: x-twitter
    -
      id: wa7FjKVl
      name: Instagram
      url: 'https://www.instagram.com/limelightsmp'
      icon: site/social-icons/instagram.svg
      icon_field: instagram
