tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: site_name
            field:
              character_limit: 0
              type: text
              display: 'Site Name'
              instructions: 'Shown in the nav and footer.'
              listable: hidden
              input_type: text
          -
            handle: personality
            field:
              options:
                casual: Casual
                formal: Formal
              inline: true
              type: radio
              instructions: 'Subtly alter the personality of the site.'
              listable: hidden
              display: Personality
          -
            handle: show_signup
            field:
              type: toggle
              instructions: 'Show the newsletter signup form on the blog.show pages.'
              listable: hidden
              display: 'Show Signup'
          -
            handle: social
            field:
              fields:
                -
                  handle: name
                  field:
                    type: text
                    display: Name
                -
                  handle: url
                  field:
                    character_limit: 0
                    type: text
                    display: URL
                -
                  handle: icon_field
                  field:
                    directory: public/assets/fontawesomeicons
                    type: icon
                    display: 'Icon Field'
                    listable: hidden
                    instructions_position: above
                    visibility: visible
                    replicator_preview: true
                    hide_display: false
              mode: table
              add_row: 'Add Link'
              reorderable: true
              type: grid
              instructions: 'Set social media links for the footer.'
              display: Social
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              fullscreen: true
              hide_display: false
